music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

myProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('home/', TemplateView.as_view(template_name='registration/home.html')),
    path('', include('tst.urls')),
    path('music/', include('music.urls'))
]

tst/urls.py
from django.urls import path
from . import views

app_name = 'tst'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('question/<int:id>', views.question, name='question'),
    path('question/<int:id>/addChoice', views.addChoice, name='addChoice'),
    path('question/addQuestion', views.addQuestion, name='addQuestion'),
    path('question/<int:id>/update', views.updateQuestion, name='updateQuestion'),
    path('question/<int:id>/delete', views.deleteQuestion, name='deleteQuestion'),
]

music/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=250)
    surname = models.CharField(max_length=250)

    @property
    def full_name(self):
        return self.name + self.surname


class Group(models.Model):
    name = models.CharField(max_length=250)
    members = models.ManyToManyField(Person)


class Music(models.Model):
    track_name = models.CharField(max_length=250)
    time = models.FloatField(max_length=3)
    author = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return 'Name: {}, time {}'.format(self.track_name, self.time)

tst/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Question(models.Model):
    text = models.CharField(max_length=200)
    date = models.DateTimeField()

    def __str__(self):
        return "\"{}\" at: {}".format(self.text, self.date.ctime())

    def countChooses(self):
        return self.choice_set.count()

    countChooses.short_description = 'Chooses'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    mark = models.SmallIntegerField()
    date = models.DateTimeField()

    def __str__(self):
        return "Question: {}, {}* at: {}".format(self.question, self.mark, self.date.ctime())

    def isRecent(self):
        now = timezone.now()
        if now - timezone.timedelta(days=1) <= self.date <= now:
            return True
        else:
            return False

    isRecent.boolean = True
    isRecent.short_description = 'recent'

music/views.py
from django.shortcuts import render
from django.views import generic
from .models import Music, Group, Person


# Create your views here.

class IndexView(generic.ListView):
    model = Music
    template_name = 'music/index.html'
    context_object_name = 'music'

    def get_queryset(self):
        return Music.objects.all()

tst/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseBadRequest
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from tst.models import Question


class IndexView(generic.ListView):  # generic view
    template_name = 'tst/index.html'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.all()


# def index(request):   # regular view
#     questions = Question.objects.all()
#     result = {
#         'questions': questions
#     }
#     return render(request, "tst/index.html", result)

def question(request, id):
    question = get_object_or_404(Question, id=id)
    chooses = question.choice_set.all().order_by('date')
    user = request
    result = {
        'question': question,
        'chooses': chooses
    }
    return render(request, "tst/question.html", result)


def addChoice(request, id):
    mark = int(request.POST['mark'])
    if mark < 0 or mark > 5:
        return HttpResponseBadRequest('Wrong mark')

    question = get_object_or_404(Question, id=id)
    question.choice_set.create(mark=mark, date=timezone.now())
    return redirect(reverse('tst:question', args={id}))


def addQuestion(request):
    question = Question()
    question.date = timezone.now()
    question.text = request.POST['text']
    question.save()
    return redirect(reverse('tst:index'))


def updateQuestion(request, id):
    question = get_object_or_404(Question, id=id)
    newText = request.POST['text']
    if newText:
        question.text = newText
        question.date = timezone.now()
        question.save()
        return redirect(reverse('tst:index'))
    else:
        return HttpResponseBadRequest('Wrong input')


def deleteQuestion(request, id):
    question = get_object_or_404(Question, id=id)
    question.choice_set.all().delete()
    question.delete()
    return redirect(reverse('tst:index'))

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/tst/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>


    {% block styles %} {% endblock %}

    <meta charset="UTF-8">
    <title>{% block title %}Index{% endblock %}</title>
</head>


<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">Django TestField</a>
        <a href="#" data-target="mobile-sidebar" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
                <li><a class='dropdown-trigger' data-target="userActions">{{ user.username }}</a></li>

                <ul id='userActions' class='dropdown-content'>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>

            {% else %}
                <li><a href="{% url '' %}">Register</a></li>
                <li><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}

        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-sidebar">
    <li><a href="#">#</a></li>
</ul>

<body>
{% block main %}{% endblock %}
</body>

<script>
    $(document).ready(function () {
        $('.sidenav').sidenav();
    });

    $('.dropdown-trigger').dropdown();
</script>
{% block scripts %}{% endblock %}

</html>

templates/music/index.html
{% extends 'layout.html' %}

{% block title %} Music{% endblock %}
{% block main %}
    <p>hey</p>
    {% for item in music %}
        <p>{{ item.track_name }} | {{ item.time }} : <a href="#">{{ item.group.name|default:'Unknown' }}</a>
            from: {{ item.author.full_name|default:'Unknown' }}</p>
    {% endfor %}
{% endblock %}

templates/tst/index.html
{% extends "layout.html" %}
{% block main %}
    <h3>All questions:</h3>
    {% if questions %}
        {% for question in questions %}
            <p><a href="{% url 'tst:question' question.id %}">{{ question.text }}</a> at {{ question.date }}
                <a href="{% url 'tst:deleteQuestion' question.id %}">Delete</a>
            </p>
        {% endfor %}
    {% endif %}

    <h3>Add question</h3>

    <form action="{% url 'tst:addQuestion' %}" method="post">
        {% csrf_token %}
        <textarea name="text" cols="30" rows="3"></textarea>
        <br>
        <input type="submit">
    </form>
{% endblock %}

templates/tst/question.html
{% extends 'layout.html' %}

{% block main %}
    <h3>{{ question.text }}</h3>

    <form action="{% url 'tst:updateQuestion' question.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="text">
        <input type="submit" value="Update">
    </form>

    <h4>Marks:</h4>
    {% if chooses.count == 0 %}
        <p>No marks</p>
    {% else %}
        {% load tz %}
        {% for choice in chooses %}
            <p>{{ choice.mark }} stars at
                <small>
                    {{ choice.date|localtime }}
                </small>
            </p>
        {% endfor %}
    {% endif %}
    <br>
    <form action="{% url 'tst:addChoice' question.id %}" method="post">
        {% csrf_token %}
        <input max="5" min="1" placeholder="5" value="5" name="mark" type="number">
        <input type="submit">
    </form>
{% endblock %}